// data.js
export const options = {
  CPU: ["Intel i7", "AMD Ryzen 9", "Intel i5"],
  GPU: ["NVIDIA RTX 3060", "AMD Radeon RX 6700", "GTX 1660"],
  RAM: ["8GB", "16GB", "32GB"],
  SSD: ["512GB SSD", "1TB SSD"],
  HDD: ["1TB HDD", "2TB HDD"],
  Motherboard: ["ASUS Prime", "MSI Pro", "Gigabyte B450"],
  PowerSupply: ["500W", "750W", "1000W"],
  CPUCooler: ["Cooler Master", "Corsair Hydro", "Noctua NH-D15"],
  ComputerCase: ["NZXT H510", "Corsair 4000D", "Phanteks Eclipse"],
  WiFiCard: ["Intel AX200", "TP-Link AC1300"],
  Ports: ["Standard", "Enhanced USB", "Thunderbolt"],
};

export const prices = {
  CPU: { "Intel i7": 300, "AMD Ryzen 9": 400, "Intel i5": 200 },
  GPU: { "NVIDIA RTX 3060": 500, "AMD Radeon RX 6700": 450, "GTX 1660": 300 },
  RAM: { "8GB": 50, "16GB": 80, "32GB": 120 },
  SSD: { "512GB SSD": 100, "1TB SSD": 150 },
  HDD: { "1TB HDD": 60, "2TB HDD": 90 },
  Motherboard: { "ASUS Prime": 150, "MSI Pro": 130, "Gigabyte B450": 120 },
  PowerSupply: { "500W": 60, "750W": 80, "1000W": 100 },
  CPUCooler: { "Cooler Master": 70, "Corsair Hydro": 100, "Noctua NH-D15": 90 },
  ComputerCase: { "NZXT H510": 80, "Corsair 4000D": 90, "Phanteks Eclipse": 85 },
  WiFiCard: { "Intel AX200": 30, "TP-Link AC1300": 25 },
  Ports: { "Standard": 0, "Enhanced USB": 20, "Thunderbolt": 40 },
};

// Sample image URLs
export const productImages = {
  "Intel i7": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Intel_Core_i7_%2811th_generation%2C_logo%29.svg/1024px-Intel_Core_i7_%2811th_generation%2C_logo%29.svg.png",
  "AMD Ryzen 9": "https://pcbworldtech.com/wp-content/uploads/2024/09/AMD-Ryzen-9-9950x-11.jpg",
  "Intel i5": "https://m.media-amazon.com/images/I/518PbvkOn4L._AC_UF350,350_QL80_.jpg",
  "NVIDIA RTX 3060": "https://images-cdn.ubuy.co.in/6370d8671264691a0b4d0d27-pny-geforce-rtx-3060-ti-8gb-verto-dual.jpg",
  "AMD Radeon RX 6700 ": "https://tpucdn.com/gpu-specs/images/c/3716-front.jpg",
  "GTX 1660": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGqBYOC8Sp-FENhf--_XG5lkrEd51CUHmkrA&s",
  "8GB": "https://m.media-amazon.com/images/I/710WlEKvWmL.jpg",
  "16GB": "https://rukminim2.flixcart.com/image/750/900/kfsl18w0/ram/s/z/r/adata-premier-3200mhz-16gb-ram-ddr4-for-laptop-original-imafw6htgpgnu2uu.jpeg?q=20&crop=false",
  "32GB": "https://content.crucial.com/content/dam/crucial/dram-products/laptop/images/product/crucial-ddr4-sodimm-image1.psd.transform/medium-png/image.png",
  "512GB SSD": "https://images-cdn.ubuy.co.in/64a52173958285471b5c8750-samsung-ssd-512gb-pm991-m-2-2230-30mm.jpg",
  "1TB SSD": "https://m.media-amazon.com/images/I/71tLxUwioYL._AC_UF1000,1000_QL80_.jpg",
  "1TB HDD": "https://rukminim2.flixcart.com/image/850/1000/jsdj8nk0/internal-hard-drive/p/k/u/wd-western-digital-caviar-blue-wd10ezex-original-imafdxtnahtjehgd.jpeg?q=90&crop=false",
  "2TB HDD": "https://m.media-amazon.com/images/I/8182vlb6ilL._AC_UF350,350_QL80_.jpg",
  "ASUS Prime": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-yjSHXwUo23waRHenxMBqDxXNFQ08Q8Tqvw&s",
  "MSI Pro": "https://m.media-amazon.com/images/I/61ZBC1Z7ttL._AC_UF1000,1000_QL80_.jpg",
  "Gigabyte B450": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStVV0BSJ__Hl7g8_rFIiCJj6JB5TJDWuQBWg&s",
  "500W": "https://rukminim2.flixcart.com/image/750/900/k5wse4w0/psu/f/y/q/cooler-master-500w-power-supply-original-imafzhsfe6htjmrb.jpeg?q=20&crop=false",
  "750W": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnThkbLKan1fvO2Yrtg0Ry2-TKIeQBHW-2Ww&s",
  "1000W": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbhbnjwPfXnPWkyLVj1dw29qPfpuJsSn6aiA&s",
  "Cooler Master": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiwbnMgG5mkcMmPMDF3wg3KKMtlNNK7gRhLg&s",
  "Corsair Hydro": "https://5.imimg.com/data5/SV/CE/MY-15746136/abacus-corsair-h45-2300-rpm-hydro-series-liquid-cpu-cooler.jpg",
  "Noctua NH-D15": "https://m.media-amazon.com/images/I/91t48GBv8TL._AC_UF1000,1000_QL80_.jpg",
  "NZXT H510": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiMHo-IEYfTpQwm7GyM5TUoNUeJp6e05LrAw&s",
  "Corsair 4000D": "https://www.ezpzsolutions.in/wp-content/uploads/2020/10/Corsair-4000D-Airflow-Cabinet-Black-5.jpg",
  "Phanteks Eclipse": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQO8EFCefE4ZpeM_gzVEbLzF6OYGQOr7ZoFg&s",
  "Intel AX200": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMFtYR0xV4xWWgz7-WPUtbJ8wwqnSVqwBKkw&s",
  "TP-Link AC1300": "https://m.media-amazon.com/images/I/614UCEgcQWL.jpg",
  "Standard": "https://m.media-amazon.com/images/I/516v6WdUgGL._SR290,290_.jpg",
  "Enhanced USB": "",
  "Thunderbolt": "",

};

export const preBuiltPCs = [
  {
    id: 1,
    name: "Gaming Beast X500",
    description: 'A high-performance gaming PC for the ultimate experience.',
    image: ["https://res.cloudinary.com/jawa/image/upload/f_auto,ar_5:4,c_fill,w_3840,q_auto/production/listings/zrl4fl1n66aif4xqo5vi",
      "https://res.cloudinary.com/jawa/image/upload/f_auto,ar_1:1,c_fill,w_1080,q_auto/production/listings/eguxiox5xygjtfkaeddy",
      "https://res.cloudinary.com/jawa/image/upload/f_auto,ar_1:1,c_fill,w_1080,q_auto/production/listings/e0werltftmp3r8vilrmr",
      "https://res.cloudinary.com/jawa/image/upload/f_auto,ar_1:1,c_fill,w_1080,q_auto/production/listings/yjulxk6mrn3d13b7dstr",
      "https://res.cloudinary.com/jawa/image/upload/f_auto,ar_1:1,c_fill,w_1080,q_auto/production/listings/zoaoyqtruxgq3kybvgzt",
    ],
    specs: {
      platform: [{ name: "Platform", value: "amd", price: 5000 }],
      CPU: [{ name: "CPU", value: "Core i5 - 14400 Upto 4.7GHz", price: 9000 }],
      Motherboard: [{ name: "Motherboard", value: "MSI B450 Tomahawk", price: 2500 }],
      RAM: [
        { name: "RAM", value: "16x1 - Gskill Ripjaws S5 5200Mhz DDR5 16GB", price: 1000 },
        { name: "RAM", value: "32GB DDR4", price: 500 },
      ],
      Storage1: [
        { name: "Storage 1", value: "1TB - WD Blue SN550 NVMe M.2", price: 1998 },
        { name: "Storage 1", value: "2TB - WD Blue SN550 NVMe M.2", price: 2998 },
      ],
      Storage2: [
        { name: "Storage 2", value: "2TB - Seagate Barracuda 7200RPM", price: 1500 },
        { name: "Storage 2", value: "5TB - Seagate Barracuda 7200RPM", price: 2500 },
      ],
      LiquidCooler: [{ name: "Liquid Cooler", value: "Cooler Master Hyper 212", price: 500 }],
      GraphicCard: [{ name: "Graphic Card", value: "Arc A380 - Intel 6GB", price: 8000 }],
      smps: [{ name: "SMPS", value: "Deepcool - PK450D Bronze", price: 1000 }],
      Cabinet: [{ name: "Cabinet", value: "NZXT H510", price: 2000 }],
    },
    otherTechnicalDetails: [
      { name: "WIFI", value: "802.11ax Wi-Fi 6 (Dual Band)" },
      { name: "BLUETOOTH", value: "Bluetooth 5.1" },
      { name: "LIGHTING", value: "RGB LED Lighting with 16.8M colors" },
      { name: "FAN CONTROL", value: "Supports up to 4 fans" },
      { name: "FRONT PORTS", value: "2x USB 3.0, 1x USB-C, 1x Audio Jack" },
      { name: "REAR PORTS", value: "1x HDMI 2.1, 4x USB 3.1, 1x Ethernet (RJ45)" },
      { name: "DIMENSIONS", value: "18 x 8 x 16 inches (LxWxH)" },
      { name: "WEIGHT", value: "15 kg (33 lbs)" },
    ],   
    notes: [
      "This is a pre-build system. We will assemble the PC free of cost with every individual component mentioned.",
      "As it is a pre-build system, the package of the individual product will be opened for the PC build.",
      "It may take up to 4-5 working days to build and test the PC before shipment.",
      "Goods once sold will not be taken back or exchanged. Once invoice is made, it cannot be modified or cancelled for any reasons thereof.",
      "Individual product warranty is provided by the respective brands/manufacturers of the PC components.",
      "In case of modification, please email to us._____",
      "The package box is properly sealed and packed with our top-tier packing material to prevent any damage or physical harm.",
    ],
    code: '5525855555',
    inStock: true,
    price: 1200,
    category: "Gaming PCs",
    popularity: 5,
    dateAdded: new Date('2023-10-10'),
    originalPrice: 1499.00,
    discount: 20,
    bonuses: 45,
    reviews: [],
  },
  {
    id: 2,
    name: "Workstation Pro Z300",
    description: 'A high-performance gaming PC for the ultimate experience.',
    image: ["https://m.media-amazon.com/images/I/81KAJON1TXL._AC_UF894,1000_QL80_.jpg",
      "",
      "",
      "",
      "",
    ],
    specs: {
      platform: [{ name: "Platform", value: "amd" }],
      CPU: [{ name: "CPU", value: "Core i5 - 14400 Upto 4.7GHz" }],
      Motherboard: [{ name: "Motherboard", value: "MSI B450 Tomahawk" }],
      RAM: [{ name: "RAM", value: "16x1 - Gskill Ripjaws S5 5200Mhz DDR5 16GB" }],
      Storage1: [{ name: "Storage 1", value: "1TB - WD Blue SN550 NVMe M.2" }],
      Storage2: [{ name: "Storage 2", value: "2TB - Seagate Barracuda 7200RPM" }],
      LiquidCooler: [{ name: "Liquid Cooler", value: "Cooler Master Hyper 212" }],
      GraphicCard: [{ name: "Graphic Card", value: "Arc A380 - Intel 6GB" }],
      smps: [{ name: "SMPS", value: "Deepcool - PK450D Bronze" }],
      Cabinet: [{ name: "Cabinet", value: "NZXT H510" }],
    },
    otherTechnicalDetails: [
      { name: "WIFI", value: "____" },
      { name: "BULETOOTH", value: "____" },
      { name: "LIGHTING", value: "____" },
      { name: "FAN CONTROL", value: "____" },
      { name: "FRONT PORTS", value: "____" },
      { name: "REAR PORTS", value: "____" },
      { name: "DIMENSIONS", value: "____" },
      { name: "WEIGHT", value: "____" },
    ],
    notes: [
      "This is a pre-build system. We will assemble the PC free of cost with every individual component mentioned.",
      "As it is a pre-build system, the package of the individual product will be opened for the PC build.",
      "It may take up to 4-5 working days to build and test the PC before shipment.",
      "Goods once sold will not be taken back or exchanged. Once invoice is made, it cannot be modified or cancelled for any reasons thereof.",
      "Individual product warranty is provided by the respective brands/manufacturers of the PC components.",
      "In case of modification, please email to us._____",
      "The package box is properly sealed and packed with our top-tier packing material to prevent any damage or physical harm.",
    ],
    code: '5525855555',
    price: 1899,
    category: "Office PCs",
    popularity: 8,
    dateAdded: new Date('2023-08-15'),
    originalPrice: 1368.00,
    discount: 20,
    bonuses: 45,
    reviews: [],
  },
  {
    id: 3,
    name: "Budget Starter S100",
    description: 'A high-performance gaming PC for the ultimate experience.',
    image: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQu5D2oH_2uYIhWUIkTYkyrx8RHwXl3KMrtw&s",
      "",
      "",
      "",
      "",
    ],
    keySpecs: [
      { name: 'Weight', value: '1.5 kg' },
      { name: 'Battery Life', value: '10 hours' },
    ],
    specs: {
      CPU: [
        { name: "Brand", value: "AMD" },
        { name: "Series", value: "Ryzen 5" },
        { name: "Model", value: "Ryzen 5 7600" },
        { name: "Socket", value: "AM5" },
        { name: "Core Count", value: "8 cores" },
        { name: "Cooler Type", value: "AIO" },
      ],
      GPU: [
        { name: "Chipset", value: "AMD" },
        { name: "Brand", value: "AMD" },
        { name: "Series", value: "Radeon RX 7800 XT" },
        { name: "Memory", value: "16GB" },
      ],
      Memory: [
        { name: "Capacity", value: "32GB" },
        { name: "Type", value: "DDR5" },
        { name: "Form Factor", value: "DIMM (Desktop)" },
      ],
    },
    technicalDetails: ['Detail 1', 'Detail 2', 'Detail 3'],
    code: '5525855555',
    price: 799,
    category: "All-Rounder PCs",
    popularity: 3,
    dateAdded: new Date('2023-09-05'),
    originalPrice: 1368.00,
    discount: 20,
    bonuses: 45,
    reviews: [],
  },
];

export const refurbishedLaptops = [
  {
    id: 1,
    name: "Gaming Laptops",
    code: "LAP456",
    description: "Reliable refurbished laptop with solid performance.",
    image: [
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08192495_33.png",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08192437_33.png",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08192466_2_16.png",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/9/Y/9Y0Y8PA-4_T1716537789.png",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/r/o/roku_blue_ports_10.jpg",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/r/o/roku_blue_dimension_10.jpg",
    ],
    specs: {
      CPU: [{ name: "Intel i5", value: "Core i5-10210U" }],
      RAM: [{ name: "RAM", value: "16GB DDR4" }],
      Storage: [{ name: "Storage", value: "512GB SSD" }],
      GraphicCard: [{ name: "Graphic Card", value: "Arc A380 - Intel 6GB" }],
      display: [{ name: "Display", value: "15.6-inch FHD" }],
      os: [{ name: "OS", value: "Windows 10" }],
    },
    notes: [
      "This is a pre-build system. We will assemble the PC free of cost with every individual component mentioned.",
      "As it is a pre-build system, the package of the individual product will be opened for the PC build.",
      "It may take up to 4-5 working days to build and test the PC before shipment.",
      "Goods once sold will not be taken back or exchanged. Once invoice is made, it cannot be modified or cancelled for any reasons thereof.",
      "Individual product warranty is provided by the respective brands/manufacturers of the PC components.",
      "In case of modification, please email to us._____",
      "The package box is properly sealed and packed with our top-tier packing material to prevent any damage or physical harm.",
    ],
    condition: "Excellent",
    price: 15799,
    category: "Gaming Laptops",
    inStock: true,
    originalPrice: 999,
    discount: 20,
    popularity: 3,
    dateAdded: new Date('2023-09-05'),
    bonuses: 50,
    reviews: [],
  },
  {
    id: 2,
    name: "Business Laptops",
    code: "LAP456",
    description: "Reliable refurbished laptop with solid performance.",
    image: [
      "https://m.media-amazon.com/images/I/71BomIO87UL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71ZPlFlqukL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71s-npS4kkL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71Hb57EtNBL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71fuU52wyiL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71Dz4SUxU-L._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71SIjkA+ooL._SX679_.jpg",
    ],
    keySpecs: [
      { name: 'Weight', value: '1.5 kg' },
      { name: 'Battery Life', value: '10 hours' },
    ],
    specs: {
      CPU: [{ name: "Intel i5", value: "Core i5-10210U" }],
      RAM: [{ name: "RAM", value: "16GB DDR4" }],
      Storage: [{ name: "Storage", value: "512GB SSD" }],
    },
    price: 10899,
    category: "Business Laptops",
    originalPrice: 999,
    discount: 20,
    popularity: 5,
    dateAdded: new Date('2023-08-15'),
    bonuses: 50,
    reviews: [],
  },
  {
    id: 3,
    name: "Student Laptops",
    code: "LAP456",
    description: "Reliable refurbished laptop with solid performance.",
    image: [
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c07991100-touch.png",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c07990976.png",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08255980.png",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/d/e/dezik_nsilver_ports_4.png",
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c07991100.png",
    ],
    keySpecs: [
      { name: 'Weight', value: '1.5 kg' },
      { name: 'Battery Life', value: '10 hours' },
    ],
    specs: {
      CPU: [{ name: "Intel i5", value: "Core i5-10210U" }],
      RAM: [{ name: "RAM", value: "16GB DDR4" }],
      Storage: [{ name: "Storage", value: "512GB SSD" }],
    },
    price: 21099,
    category: "Student Laptops",
    originalPrice: 999,
    discount: 20,
    popularity: 10,
    dateAdded: new Date('2023-10-10'),
    bonuses: 50,
    reviews: [],
  },
];  